sue445/rubicure

CHANGELOG.md, README.md, config/girls/001_unmarked.yml, config/girls/002_max_heart.yml, config/girls/003_splash_star.yml, config/girls/004_yes.yml, config/girls/005_yes_gogo.yml, config/girls/006_fresh.yml, config/girls/007_heart_catch.yml, config/girls/008_suite.yml, config/girls/009_smile.yml, config/girls/010_dokidoki.yml, config/girls/011_happiness_charge.yml, spec/core_spec.rb, spec/girl_spec.rb
#67 
```ruby
yayoi = Cure.peace
yayoi.cast_name
#=> "金元寿子"
pp Precure.all_stars.map(&:cast_name)
["本名陽子",
"ゆかな",
"田中理恵",
"樹元オリエ",
"榎本温子",
"三瓶由布子",
"竹内順子",
"伊瀬茉莉也",
"永野愛",
"前田愛",
"仙台エリ",
"沖佳苗",
"喜多村英梨",
"中川亜紀子",
"小松由佳",
"水樹奈々",
"水沢史絵",
"桑島法子",
"久川綾",
"小清水亜美",
"折笠富美子",
"豊口めぐみ",
"大久保瑠美",
"福圓美里",
"田野アサミ",
"金元寿子",
"井上麻里奈",
"西村ちなみ",
"生天目仁美",
"寿美菜子",
"渕上舞",
"宮本佳那子",
"釘宮理恵",
"中島愛",
"潘めぐみ",
"北川里奈",
"戸松遥"]
```
=> Impl Girl#cast_name

CHANGELOG.md, README.md, config/girls/001_unmarked.yml, config/girls/002_max_heart.yml, config/girls/003_splash_star.yml, config/girls/004_yes.yml, config/girls/005_yes_gogo.yml, config/girls/006_fresh.yml, config/girls/007_heart_catch.yml, config/girls/008_suite.yml, config/girls/009_smile.yml, config/girls/010_dokidoki.yml, config/girls/011_happiness_charge.yml, lib/rubicure/girl.rb, spec/core_spec.rb, spec/girl_spec.rb
```ruby
Cure.peace.color
#=> "yellow"
Cure.happy.color
#=> "pink"
Cure.peace.yellow?
#=> true
Cure.peace.pink?
#=> false
Cure.happy.pink?
#=> true
Rubicure::Girl.colors
#=> [:black, :blue, :green, :pink, :purple, :red, :white, :yellow]
Precure.all_stars.select(&:pink?).map(&:precure_name)
#=> ["キュアブルーム", "キュアドリーム", "キュアピーチ", "キュアブロッサム", "キュアメロディ", "キュアハッピー", "キュアハート", "キュアラブリー"]
Precure.all_stars.select(&:yellow?).map(&:precure_name)
#=> ["シャイニールミナス", "キュアレモネード", "キュアパイン", "キュアサンシャイン", "キュアミューズ", "キュアピース", "キュアロゼッタ", "キュアハニー"]
```
=> Impl Girl#color

config/girls/001_unmarked.yml, config/girls/002_max_heart.yml, config/girls/003_splash_star.yml, config/girls/004_yes.yml, config/girls/005_yes_gogo.yml, config/girls/006_fresh.yml, config/girls/007_heart_catch.yml, config/girls/008_suite.yml, config/girls/009_smile.yml, config/girls/010_dokidoki.yml, config/girls/011_happiness_charge.yml, config/girls/012_go_princess.yml, config/series.yml, spec/girl_spec.rb, spec/series_spec.rb
```ruby
irb(main):002:0> Precure.all_stars.map(&:girl_name)
=> ["cure_black", "cure_white", "shiny_luminous", "cure_bloom", "cure_egret", "cure_dream", "cure_rouge", "cure_lemonade", "cure_mint", "cure_aqua", "milky_rose", "cure_peach", "cure_berry", "cure_pine", "cure_passion", "cure_blossom", "cure_marine", "cure_sunshine", "cure_moonlight", "cure_melody", "cure_rhythm", "cure_beat", "cure_muse", "cure_happy", "cure_sunny", "cure_peace", "cure_march", "cure_beauty", "cure_heart", "cure_diamond", "cure_rosetta", "cure_sword", "cure_ace", "cure_lovely", "cure_princess", "cure_honey", "cure_fortune", "cure_flora", "cure_mermaid", "cure_twinkle", "cure_scarlett"]
irb(main):005:0> Precure.map(&:series_name)
=> ["unmarked", "max_heart", "splash_star", "yes", "yes_gogo", "fresh", …
```
=> Add own uniq name

lib/rubicure/series.rb
=> Add to_json args

README.md, lib/rubicure/cure.rb
```ruby
scarlett = Cure.scarlett
scarlett.name
=> "紅城トワ"
!scarlett
scarlett.name
=> "トワイライト"
```
=> Support turnover to towa-sama

CHANGELOG.md, Gemfile, README.md, config/girls/013_maho_girls.yml, config/series.yml, lib/rubicure.rb, lib/rubicure/cure.rb, lib/rubicure/girl.rb, rubicure.gemspec, spec/core_spec.rb, spec/girl_spec.rb, spec/series_spec.rb, spec/spec_helper.rb
```ruby
mirai = Cure.miracle
mirai.name
mirai.cure_up_rapapa! :diamond
mirai.transform! :diamond
キュアップ・ラパパ！　ダイヤ！
ミラクル・マジカル・ジュエリーレ！
ふたりの奇跡！キュアミラクル！
魔法つかいプリキュア！！
mirai.name
mirai.attack!
リンクルステッキ！
ダイヤ！永遠の輝きを私達の手に！
フルフルリンクル！
プリキュア！ダイヤモンドエターナル！
```
=> Add maho girls precure

config/girls/013_maho_girls.yml
ref
* http://precure.channel.or.jp/maho/stone/stone_diamond.php
* http://precure.channel.or.jp/maho/stone/stone_ruby.php
=> Fix typo and tweak attack message of maho girls

CHANGELOG.md, config/girls/013_maho_girls.yml
ref
* http://precure.channel.or.jp/maho/stone/stone_sapphire.php
=> Add sapphire style

.travis.yml, CHANGELOG.md, README.md, config/girls/movie.yml, config/movies.yml, lib/rubicure/concerns/util.rb, lib/rubicure/core.rb, spec/core_spec.rb
```ruby
echo = Cure.echo
echo.name
echo.transform!
思いよ届け！キュアエコー！
echo.name
echo.attack!
世界に響け、みんなの想い！！
プリキュア・ハートフルエコー！！
```
```ruby
Precure.all_stars.count
Precure.all_stars(:new_stage).count
Precure.all_stars(:new_stage).include?(Cure.echo)
Precure.all_stars(:new_stage2).count
Precure.all_stars(:new_stage3).count
Precure.all_stars(:new_stage3).include?(Cure.echo)
Precure.all_stars(:spring_carnival).count
Precure.all_stars(:sing_together_miracle_magic).count
Precure.all_stars(:sing_together_miracle_magic).include?(Cure.echo)
```
=> Add Cure Echo

CHANGELOG.md, config/girls/013_maho_girls.yml
ref
* http://precure.channel.or.jp/maho/stone/stone_topaz.php
=> Add topaz style

config/girls/013_maho_girls.yml, config/series.yml, rubicure.gemspec, spec/core_spec.rb
```ruby
$ be irb -rubicure
irb(main):001:0> ha_chan = Cure.felice
irb(main):002:0> ha_chan.name
=> "花海ことは"
irb(main):003:0> ha_chan.cure_up_rapapa!(:emerald)
キュアップ・ラパパ！エメラルド！
フェリーチェ・ファンファン・フラワーレ！
あまねく生命に祝福を！キュアフェリーチェ！
irb(main):004:0> ha_chan.name
=> "キュアフェリーチェ"
irb(main):005:0> ha_chan.attack!
フラワーエコーワンド！
エメラルド！
キュアー・アップ！
プリキュア！エメラルド・リンカネーション！
```
=> Add cure felice

lib/rubicure/series.rb, spec/series_spec.rb
=> Fix DEPRECATION WARNING with activesupport 5.0+

CHANGELOG.md, config/girls/012_go_princess.yml
=> Bugfix: Cure flora can not transform with `princess_engage!`

config/girls/013_maho_girls.yml
=> Apply block style of yaml to the transform messages.

README.md, config/girls/011_happiness_charge.yml, config/girls/012_go_princess.yml, examples/all.rb, lib/rubicure/girl.rb, spec/girl_spec.rb
```ruby
irb(main):002:0> Cure.princess.human_name
=> "白雪ひめ"
irb(main):003:0> Cure.princess.full_name
=> "ヒメルダ・ウインドウ・キュアクイーン・オブ・ザ・ブルースカイ"
irb(main):004:0> Cure.scarlet.human_name
=> "紅城トワ"
irb(main):005:0> Cure.scarlet.full_name
=> "プリンセス・ホープ・ディライト・トワ"
```
`#full_name` returns `#human_name` when girl doe's not have `#human_full_name`
```ruby
irb(main):006:0> Cure.miracle.human_name
=> "朝日奈みらい"
irb(main):007:0> Cure.miracle.full_name
=> "朝日奈みらい"
```
Close #134
=> Impl Girl#full_name

README.md, config/girls/movie.yml, lib/rubicure/core.rb, spec/core_spec.rb
```ruby
irb(main):001:0> Precure.all_stars.count
=> 44
irb(main):002:0> Precure.all_stars.map(&:precure_name)
=> ["キュアブラック", "キュアホワイト", "シャイニールミナス", "キュアブルーム", "キュアイーグレット", "キュアドリーム", "キュアルージュ", "キュアレモネード", "キュアミント", "キュアアクア", "ミルキィローズ", "キュアピーチ", "キュアベリー", "キュアパイン", "キュアパッション", "キュアブロッサム", "キュアマリン", "キュアサンシャイン", "キュアムーンライト", "キュアメロディ", "キュアリズム", "キュアビート", "キュアミューズ", "キュアハッピー", "キュアサニー", "キュアピース", "キュアマーチ", "キュアビューティ", "キュアハート", "キュアダイヤモンド", "キュアロゼッタ", "キュアソード", "キュアエース", "キュアラブリー", "キュアプリンセス", "キュアハニー", "キュアフォーチュン", "キュアフローラ", "キュアマーメイド", "キュアトゥインクル", "キュアスカーレット", "キュアミラクル", "キュアマジカル", "キュアフェリーチェ"]
irb(main):003:0> Precure.all_stars.include?(Cure.echo)
=> false
```
```ruby
irb(main):001:0> Precure.all_girls.count
=> 45
irb(main):002:0> Precure.all_girls.map(&:precure_name)
=> ["キュアブラック", …
```
=> Add Precure.all_girls (a.k.a. Precure.all)

config/girls/014_a_la_mode.yml, config/series.yml, lib/rubicure/core.rb, lib/rubicure/version.rb, spec/core_spec.rb, spec/series_spec.rb
=> Add kirakira precure alamode

config/girls/014_a_la_mode.yml, config/series.yml, spec/core_spec.rb
Fixed #148
via. https://twitter.com/pps_as/status/873829689269166080
=> Fix typo: macaroon -> macaron

config/girls/014_a_la_mode.yml, spec/rubicure/core_spec.rb, spec/rubicure/girl_spec.rb
Link
* http://www.toei-anim.co.jp/tv/precure/character/chara10.php
* https://www.asahi.co.jp/precure/kirakira/character/cureparfait.html#category
* http://precure.channel.or.jp/alamode/goods/details.php?detail=4549660040521000
* http://precure.channel.or.jp/alamode/goods/details.php?detail=4549660040194000
=> Add cure parfait

rubicure.gemspec, spec/rubicure/series_spec.rb, spec/spec_helper.rb
=> Fixed rubocop offenses

config/series.yml
via. https://www.asahi.co.jp/precure/kirakira/enjoyment/wallpaper.html
=> Add ended_date of Kirakira Precure A La Mode

config/girls/015_hugtto.yml, config/series.yml, spec/rubicure/core_spec.rb, spec/rubicure/series_spec.rb
* http://www.toei-anim.co.jp/tv/hugtto_precure/
* https://www.asahi.co.jp/precure/hugtto/
* http://precure.channel.or.jp/hug/
=> Add Hugtto Precure

config/movies.yml, lib/rubicure/core.rb, spec/rubicure/core_spec.rb, spec/rubicure/movie_spec.rb
http://www.precure-superstars.com/
=> Add Precure.super_stars

config/girls/015_hugtto.yml
c.f. https://twitter.com/pps_as/status/981049566819532800
=> Add Cure Etoile Birthday :birthday:

config/girls/015_hugtto.yml
=> Add birthdays of Hana and Saaya

lib/rubicure/girl.rb, rubicure.gemspec, spec/rubicure/core_spec.rb
=> Fixed. NoMethodError when transform_calls is not registered

CHANGELOG.md, config/movies.yml, spec/rubicure/core_spec.rb, spec/rubicure/movie_spec.rb
```ruby
irb(main):001:0> Precure.all_stars(:memories).count
=> 55
irb(main):002:0> Precure.all_stars(:memories).map(&:precure_name)
=> ["キュアブラック", "キュアホワイト", "シャイニールミナス", "キュアブルーム", "キュアイーグレット", "キュアドリーム", "キュアルージュ", "キュアー", "キュアパイン", "キュアパッション", "キュアブロッサム", "キュアマリン", "キュアサンシャイン", "キュアムーンライト", "キュアメロディ", "キュ", "キュアマーチ", "キュアビューティ", "キュアハート", "キュアダイヤモンド", "キュアロゼッタ", "キュアソード", "キュアエース", "キュアラブリー",ド", "キュアトゥインクル", "キュアスカーレット", "キュアミラクル", "キュアマジカル", "キュアフェリーチェ", "キュアホイップ", "キュアカスタード","キュアエール", "キュアアンジュ", "キュアエトワール", "キュアマシェリ", "キュアアムール"]
```
=> Add Precure.all_stars(:memories)

README.md, config/series.yml
あれっ、ほかのシリーズはちゃんと日曜日に終わってるのに、これだけ月曜日が最終回???
=> Hugtto precure EndDate should be 2019-01-27

README.md, config/girls/013_maho_girls.yml
キュアぱずでは紫になっていたので、たぶん紫プリキュアなんだろう
個人的な好みを言えば、やまとなでしこの2人が紫プリキュア同士になるのでアリだと思ってる
=> Cure magical's color may be purple

config/girls/016_star_twinkle.yml
cf. https://youtu.be/bwVkmPRQGOg?t=79
=> Cure Cosmo's attack message will be "Precure! Cosmo shining!"

README.md, lib/rubicure.rb, lib/rubicure/cure_cosmo.rb, spec/rubicure/cure_cosmo_spec.rb
```ruby
Cure.cosmo.transform!(:rainbow_perfume)
レインボーパフュームいくニャン！
Cure.cosmo.name
#=> one of "マオ", "ブルーキャット" or "バケニャーン"
```
Close #209
=> Impl `Cure.cosmo.transform!(:rainbow_perfume)`

rubicure.gemspec
c.f. https://guides.rubygems.org/mfa-requirement-opt-in/
=> Enable MFA requirement for gem releasing

lib/rubicure.rb
=> Fixed. `NameError: uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState` with activesupport v7.0.0

config/girls/017_healingood.yml, config/girls/018_tropical_rouge.yml, spec/config/girls_checker_spec.rb
=> Fixed. Couldn't call `#precure_operation!` and `#precure_tropical_change!`

README.md, config/girls/019_delicious_party.yml, spec/rubicure/girl_spec.rb
c.f. https://twitter.com/YuFu_toyomimasu/status/1545922777307222016
=> Fix Cure Finale color

README.md, lib/rubicure.rb, lib/rubicure/cure_finale.rb
```ruby
>> finale = Cure.finale
>> finale.name
=> "菓彩あまね"
>> !finale
>> finale.name
=> "ジェントルー"
```
=> Add turnover to Cure Finale (Amane <=> Gentle)

README.md, lib/rubicure/series.rb
ref. https://github.com/sue445/rubicure/issues/284
=> Add `#members` as alias for `#girls`

README.md, lib/rubicure/core.rb
=> Add `#all_members` as alias for `#all_girls`

gemfiles/common.gemfile
Now requires Ruby 2.7+
follow up for #322
=> Remove needless config in gemfile

README.md, config/girls/022_you_and_idol.yml
CureKiss's main colors seem to be black and purple.
https://www.toei-anim.co.jp/tv/precure/character/curekiss.php
But her item is black.
https://toy.bandai.co.jp/series/precure/item/detail/14841/
So I changed
=> Fix CureKiss color
